### ISSUE TITLE
Implement data structures

### ISSUE THREAD

**Issue by qmau94** [qmau-me/cs.java#21]
- [ ] Automatically resizing vector
- [ ] A vector (mutable array with automatic resizing)
- [ ] Hash with array using linear probing

**Comment by Gupta-Vandana** [comment]
do we have to implement ArrayList using arrays in Automatically resizing vector? @qmau94

**Comment by Tillvf** [comment]
could you specify what you need?
I do not really know what exactly you need

**Comment by Gupta-Vandana** [comment]
plzz  u tell what we have to do
